cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/data/volume_2/PrioMeter/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/data/volume_2/PrioMeter/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139890375453776: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/data/volume_2/PrioMeter/simulation/build/.conf_check_d17a70babee59afe3e1c1c75ef40e077/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib/python2.7/config-x86_64-linux-gnu\', \'-lpython2.7\']\n'
